export const friends = [
  {
    id: 1,
    name: "John Doe",
    picture: "/1.png",
    email: "john@example.com",
    days_since_contact: 12,
    status: "overdue",
    tags: ["college", "close friend"],
    bio: "Met in university. Love hiking together.",
    goal: 14,
    next_due_date: "2026-07-20"
  },
  {
    id: 2,
    name: "Sarah Johnson",
    picture: "/2.png",
    email: "sarah@example.com",
    days_since_contact: 3,
    status: "on-track",
    tags: ["work", "mentor"],
    bio: "Former team lead who gives valuable career advice.",
    goal: 7,
    next_due_date: "2026-06-27"
  },
  {
    id: 3,
    name: "Michael Brown",
    picture: "/3.png",
    email: "michael@example.com",
    days_since_contact: 25,
    status: "overdue",
    tags: ["gym", "friend"],
    bio: "Workout partner and fitness enthusiast.",
    goal: 14,
    next_due_date: "2026-06-15"
  },
  {
    id: 4,
    name: "Emily Davis",
    picture: "/4.png",
    email: "emily@example.com",
    days_since_contact: 5,
    status: "on-track",
    tags: ["family", "cousin"],
    bio: "Lives abroad and loves sharing travel stories.",
    goal: 10,
    next_due_date: "2026-06-28"
  },
  {
    id: 5,
    name: "David Wilson",
    picture: "/5.png",
    email: "david@example.com",
    days_since_contact: 18,
    status: "overdue",
    tags: ["networking", "tech"],
    bio: "Met at a developer conference last year.",
    goal: 14,
    next_due_date: "2026-06-20"
  },
  {
    id: 6,
    name: "Olivia Martinez",
    picture: "/6.png",
    email: "olivia@example.com",
    days_since_contact: 1,
    status: "on-track",
    tags: ["book club", "friend"],
    bio: "Enjoy discussing books and personal growth.",
    goal: 14,
    next_due_date: "2026-07-06"
  },
  {
    id: 7,
    name: "James Anderson",
    picture: "/7.png",
    email: "james@example.com",
    days_since_contact: 40,
    status: "overdue",
    tags: ["school", "best friend"],
    bio: "Childhood friend who moved to another city.",
    goal: 30,
    next_due_date: "2026-06-10"
  },
  {
    id: 8,
    name: "Sophia Taylor",
    picture: "/8.png",
    email: "sophia@example.com",
    days_since_contact: 6,
    status: "almost due",
    tags: ["design", "freelancer"],
    bio: "Collaborated on several creative projects.",
    goal: 10,
    next_due_date: "2026-06-29"
  },
  {
    id: 9,
    name: "Daniel Thomas",
    picture: "/9.png",
    email: "daniel@example.com",
    days_since_contact: 15,
    status: "overdue",
    tags: ["startup", "founder"],
    bio: "Entrepreneur working on an AI startup.",
    goal: 14,
    next_due_date: "2026-06-22"
  },
  {
    id: 10,
    name: "Emma White",
    picture: "/10.png",
    email: "emma@example.com",
    days_since_contact: 2,
    status: "on-track",
    tags: ["volunteer", "community"],
    bio: "Organizes local community events and workshops.",
    goal: 7,
    next_due_date: "2026-06-30"
  }
];